theme: minima
title: Personal Blog
author: Tim Lachner
description: Hi my Name is Tim and im a student of Information Systems and beginning research assistent. My main interest lie with the combination of mashine learning and combinatorial optimization. In this blog i will document my work for projects and research. This is mainly formyself but feel free to explore.
